from LinkedList import SingleLList

if __name__ == "__main__":
    list_1 = SingleLList(5)
    list_1.append(2)
    list_1.append(9)
    list_1.append(7)
    list_1.display()
    list_1.prepend(6)
    list_1.prepend(1)    
    list_1.display() 
    # result = iter(list_1)
    # print(next(result))
    # print(next(result))
    # print(next(result))
    # print(next(result))        
    # print(next(result))            
    # print(next(result))        
    # print(next(result))                
    list_1.insert(3,8)   
    list_1.insert(12,11)       
    list_1.insert(-1,-1)           
    #list_1.display()    
    print(list_1.search(8))
    print(list_1.length)
    print(list_1.pop())
    print(list_1.length)  
    list_1.display()   
    print(list_1.pop())
    print(list_1.length)  
    list_1.display()
    print(list_1.pop())
    print(list_1.length)  
    list_1.display()
    print(list_1.pop())
    list_1.display()
    print(list_1.pop(0))
    list_1.display()
    print(list_1.pop(0))
    print(list_1.pop(2))    
    print(list_1.pop(1))
    print(list_1.pop(0))    
    #print(list_1.pop(0))
    list_1.append(7)    
    list_1.append(9)        
    list_1.append(15)    
    print(list_1.pop(2))        
    print(list_1.pop())  
    list_1.append(3)          
    list_1.append(1)        
    list_1.append(6)        
    list_1.display()        
    print(list_1.remove(6))
    list_2 = SingleLList(2)
    #list_2.pop()
    #list_2.pop()
    list_2.display()
    print(list_2.remove(6))
    list_2.append(17)
    list_2.append(35)
    list_2.append(9)    
    list_2.append(21)
    list_2.append(4)
    list_2.display()
    print(list_2.find(3))
    list_2.insert(2,5) 
    list_2.insert(0,3)     
    list_2.insert(20,7)         
    list_2.display()
    print(list_2.remove(17))
    print(list_2.remove(3))    
    print(list_2.remove(2))        
    list_2.display()
    print(repr(list_2))
    print(str(list_2))

    # list_3 = SingleLList(1)
    # list_3.pop()
    # list_3.display()       
    # list_3.insert(1,2)
    # list_3.display()       

# append(value) -> None         add item at end
# prepend(value) -> None        add item at begining
# insert(index, value) -> None  add item at given index position
# pop([, index]) -> any         remove element at end by default, if pos given remove at index
# remove(value) -> int          remove the value and return the index where it removed
# search(value) -> int          search the item and return the index position
# find(index) -> any            find the index position and return the item at index    
# display() -> None             show all the items in the list for debug
 